### ISSUE TITLE
Harcoded paths in the code

### ISSUE THREAD

**Issue by artemg** [NVIDIA/flowtron#1]
https://github.com/NVIDIA/flowtron/blob/452a9e661f650d6a196fb9fe5a88242361a44bb1/text/acronyms.py#L37

https://github.com/NVIDIA/flowtron/blob/452a9e661f650d6a196fb9fe5a88242361a44bb1/text/__init__.py#L121

**Comment by miolini** [comment]
Confirm.

**Comment by erekgit** [comment]
also

filelists/ljs_audiopaths_text_sid_val_filelist.txt


/path_to_ljs/LJ045-0227.wav|and suggests the possibility, as did his note to his wife just prior to the attempt on General Walker, that he did not expect to escape at all.|0
/path_to_ljs/LJ043-0073.wav|On October nine, nineteen sixty-two he went to the Dallas office of the Texas Employment Commission|0

**Comment by rafaelvalle** [comment]
The hardcoded paths have been fixed, thank you for reporting.
`filelists/ljs_audiopaths_text_sid_val_filelist.txt` is to be edited with your own paths.

**Comment by artemg** [comment]
Wow, that was super fast!

**Comment by bakszero** [comment]
Gorgeous, super-fast fix!
