### ISSUE TITLE
What is the difference between LibriTTS2K and LibriTTS models?

### ISSUE THREAD

**Issue by ninaburns** [NVIDIA/flowtron#101]
I think LibriTTS2K was added more recently, but not positive.  Thanks!

**Comment by rafaelvalle** [comment]
Yes. LibriTTS2k was trained with approxinately 2.3 thousand speakers. It uses LibriTTS Clean 100, 360 and other 500.

**Comment by lachjames** [comment]
Thanks for this clarification - I had the same question, and I imagine others will too (so I'd suggest putting this information in the README).

For training a custom multi-speaker model, would you suggest using the LibriTTS or LibriTTS2K model for transfer learning? I can see logic to both choices:
 - With the base version, the data is cleaner.
 - With the 2k version, it's seen more data (but not all of it was high quality data).

My dataset is very clean, so I'm thinking that it might be better to use LibriTTS, but I'm curious to hear your thoughts.

Thanks :)

**Comment by rafaelvalle** [comment]
i would fine-tune each of the models you mentioned and compare.
