### ISSUE TITLE
Unable to train the model with cummulative attention

### ISSUE THREAD

**Issue by nicemanis** [NVIDIA/flowtron#106]
Hi, I wanted to try out the cummulative attention in attempt to improve the model's attention robustness. However, the training doesn't seem to be working.

![image](https://user-images.githubusercontent.com/9463816/111143349-5c943880-858e-11eb-9a70-bda77abc3674.png)

I was able to achieve reasonable results without the cummulative attention. The only thing I changed in the configuration is `"use_cumm_attention": true`. Is there anything else that should be changed? Are there any other options for improving the robustness, e.g, enforcing monotonicity?

Here are the attention weights without the cummulative attention:

![image](https://user-images.githubusercontent.com/9463816/111143898-096eb580-858f-11eb-8f6c-29d270e51cfc.png)

I'm able to produce good results for some short sentences, but most of the time the speech contains some atifacts and the attention alignemnt seems to be noisy.

**Comment by nicemanis** [comment]
According to [this comment](https://github.com/NVIDIA/flowtron/issues/69#issuecomment-698059458) it seems that I should first train the model without cummulative attention and then fine-tune it at the end with `"use_cumm_attention": true`. Is that correct?

**Comment by viveksehgal** [comment]
Yes!

**Comment by nicemanis** [comment]
Thank's, fine-tuning a pre-trained Flowtron model worked without any problems
