### ISSUE TITLE
Output length is fixed?

### ISSUE THREAD

**Issue by andi-808** [NVIDIA/flowtron#120]
Hello,

I am in the process of training from a pre-trained model (no success so far). Running inference on some of the models I’ve produced produces sound. It doesn’t matter how long my desired sentence is I wish the model to speak, the length of the sound clip produced is always 5 seconds, 410KB.

Is there something I’m missing? Is it because my models are currently garbage and won’t produce the correct output until good attention is achieved? The voice tone/timbre sounds correct, albeit gibberish.

**Comment by andi-808** [comment]
Ok, so the file size now changes now that I’ve properly trained with my data. It took a while but I’m getting speech out with my dataset. However, there is a maximum limit for the length of the utterance. 

Do I warm start with “n_text” set to a larger value? I tried this but got an error before it even started training.

**Comment by andi-808** [comment]
I managed to get the length to vary during inference.

**Comment by Bahm9919** [comment]
> I managed to get the length to vary during inference.

Can you share, how could you do that?
