### ISSUE TITLE
Inference starting repeat itself.

### ISSUE THREAD

**Issue by Bahm9919** [NVIDIA/flowtron#139]
First of all, thanks guys for your great work and support.
I have some problem with flowtron. 
Especially, the model repeating itself. And provide only 4sec sentence. 
Even if sentence has 1 sec. So its repeating itself all 4 sec.
Warmstart  using  Tacotron2(130k) which doesnt has this problem. And i got good results.
Starting for 1 flow step.
![c1e93e8c-6dba-4bd1-8e80-887a2f1681e9](https://user-images.githubusercontent.com/57631814/137430571-0baf20f6-7305-4401-883b-4ce3a1953c7c.png)
![Screenshot_1](https://user-images.githubusercontent.com/57631814/137430573-46e9a24c-4737-402c-9089-1b0d2fade1f6.png)
![Screenshot_2](https://user-images.githubusercontent.com/57631814/137430576-b6fc2896-09ad-4e6f-9254-e6092be07717.png)

Hope for your helping Rafael. @rafaelvalle

**Comment by nikich340** [comment]
> 
> 
> Solved. Need to train gate from scratch like in README.

How much epochs did you do? Also, what dataset did you use?

**Comment by Bahm9919** [comment]
> > Solved. Need to train gate from scratch like in README.
> 
> How much epochs did you do? Also, what dataset did you use?

i'm using my own collecting russian dataset. For this, it was about 50 epochs.  Need train not only gate, so gate doesnt matter for this problem, need train without attention, and training nflow2 solved this problem, and training with cummulative attention.

**Comment by nikich340** [comment]
> > > Solved. Need to train gate from scratch like in README.
> > 
> > 
> > How much epochs did you do? Also, what dataset did you use?
> 
> i'm using my own collecting russian dataset. For this, it was about 50 epochs. Need train not only gate, so gate doesnt matter for this problem, need train without attention, and training nflow2 solved this problem, and training with cummulative attention.

So you did full retraining from scratch? No way to fix it for pretrained models?

**Comment by Bahm9919** [comment]
> > > > Solved. Need to train gate from scratch like in README.
> > > 
> > > 
> > > How much epochs did you do? Also, what dataset did you use?
> > 
> > 
> > i'm using my own collecting russian dataset. For this, it was about 50 epochs. Need train not only gate, so gate doesnt matter for this problem, need train without attention, and training nflow2 solved this problem, and training with cummulative attention.
> 
> So you did full retraining from scratch? No way to fix it for pretrained models?

There is several ways to fix it.
- use your checkpoint path for gate training like in README. Training from scratch. Step 4.
- use checkpoint path for  warmstart n_flow2, 
- use checkpoint path of n_flow2 for warm start with cummulative_attention. (very recommended)
Also you can set ` use_attn_prior` to false and continue training from your checkpoint path.
