### ISSUE TITLE
Saving state_dict in the checkpoint?

### ISSUE THREAD

**Issue by adrianastan** [NVIDIA/flowtron#18]
Hi,

I was wondering why aren't you saving the state_dict in the checkpoints? It doesn't seem like you are saving it somewhere else. And this is also the case for Waveglow: https://github.com/NVIDIA/waveglow/blob/master/train.py

Thanks!

**Comment by rafaelvalle** [comment]
When running multiple experiments we find it helps to save the model in case there are changes to the code.

**Comment by adrianastan** [comment]
Ok, got it, thanks!
