### ISSUE TITLE
Unintelligible speech - inference on pre-trained models

### ISSUE THREAD

**Issue by adrianastan** [NVIDIA/flowtron#19]
I am trying to synthesise audio starting from the available pre-trained models

`python3 inference.py -c config.json -f models/flowtron_ljs.pt -w models/waveglow_256channels_universal_v4.pt -t "Hey hello there" -o output_synth/ -i 0`

but the output is not intelligible: 

https://drive.google.com/file/d/1bWpbnMoRF5lm5RYwxZNj8bomiY_WF3mA/view?usp=sharing

The alignment also looks off:

![sid0_sigma0 5_attnlayer0](https://user-images.githubusercontent.com/6659449/82468348-6282cf80-9acb-11ea-8804-b34c84d048ef.png)

![sid0_sigma0 5_attnlayer1](https://user-images.githubusercontent.com/6659449/82468393-69a9dd80-9acb-11ea-9289-c40f2a997531.png)

I tried with both LJS and LibriTTS models.

Any idea why this happens?

Thanks!

**Comment by rafaelvalle** [comment]
Add a period to the end of your sentence.

**Comment by adrianastan** [comment]
Tried that right after running the first inference, same result:
https://drive.google.com/file/d/1MHpx4GZpz8A8slnYNoQ8bJmka4Qq8BGf/view?usp=sharing

Slightly different sounds, but still not intelligible.

**Comment by rafaelvalle** [comment]
Pull from master and run the code below.

`python inference.py -c config.json -p model_config.n_speakers=1 data_config.p_arpabet=1.0 -f models/flowtron_ljs.pt -w models/waveglow_256channels_universal_v4.pt -t "Hey. Hello there." -o output_synth/ -i 0 -s 0.5 -g 0.7`

**Comment by adrianastan** [comment]
Great, that worked! Thank you very much.
