### ISSUE TITLE
why autoregressive doesn't need revertible?

### ISSUE THREAD

**Issue by xusongvae** [NVIDIA/flowtron#21]
hi, thanks for your useful codes. I wander why in affine transform, we don't need to invert the autoregressive in backward compuation? we reuse the autoregressive RNN in backward the same as in forward?

**Comment by rafaelvalle** [comment]
From the paper between Eqs. 8 and 9.
```
Here NN() can be any autoregressive causal transformation. This can be achieved by time-wise concatenation of a 0-valued vector to the input provided to NN(). The affine
coupling layer preserves invertibility for the overall network, even though NN() does not need to be invertible.
```

**Comment by xusongvae** [comment]
Thank you, I got it later! Did you see the glow-TTS and Flow-TTS two papers？ They are non-AR and around 20 times faster than Tacotron2. I wander the speed of Flowtron, how about it? Thank you~~

发件人: Rafael Valle <notifications@github.com>
答复: NVIDIA/flowtron <reply@reply.github.com>
日期: 2020年5月25日 星期一 00:47
收件人: NVIDIA/flowtron <flowtron@noreply.github.com>
抄送: "zewangzhang(张泽旺)" <zewangzhang@tencent.com>, Author <author@noreply.github.com>
主题: Re: [NVIDIA/flowtron] why autoregressive doesn't need revertible? (#21)(Internet mail)


From the paper between Eqs. 8 and 9.

Here NN() can be any autoregressive causal transformation. This can be achieved by time-wise concatenation of a 0-valued vector to the input provided to NN(). The affine

coupling layer preserves invertibility for the overall network, even though NN() does not need to be invertible.

**Comment by rafaelvalle** [comment]
Haven't read the papers yet. There has been a race to making mel-spectrogram generation faster and not enough dedication to make it sound more real.
If i remember correctly the end to end pipeline with flowtron and waveglow is at 7x real-time using naive pytorch.
