### ISSUE TITLE
How can I implement style transfer with inference.py ?

### ISSUE THREAD

**Issue by xiaoyangnihao** [NVIDIA/flowtron#22]
@rafaelvalle, @karkirowle,  I am a little confused how to implement style transfer with inference.py or with flowtron model. I just train this model with LJSpeech.

**Comment by xiaoyangnihao** [comment]
I am a little confused how to implement style transfer with inference.py or with flowtron model.
I just train this model with LJSpeech.

**Comment by rafaelvalle** [comment]
Please continue this information [here](https://github.com/NVIDIA/flowtron/issues/9) where most of the information has already been provided.
