### ISSUE TITLE
how to obtain models/waveglow_256channels_v4.pt for the Inference demo?

### ISSUE THREAD

**Issue by erekgit** [NVIDIA/flowtron#3]
I'm trying to locate the approprate waveglow_256channels_v4.pt for flowtron inference demo.  i googled and found a colab notebook and tried using it:

"%%bash
wget -N  -q https://raw.githubusercontent.com/yhgon/colab_utils/master/gfile.py
python gfile.py -u 'https://drive.google.com/open?id=1ZesPPyRRKloltRIuRnGZ2LIUEuMSVjkI' -f 'mellotron_libritts.pt'
python gfile.py -u 'https://drive.google.com/open?id=1Rm5rV5XaWWiUbIpg5385l5sh68z2bVOE' -f 'waveglow_256channels_v4.pt'"

---
Results:

python inference.py -c config.json -f models/flowtron_ljs.pt -w models/waveglow_256channels_v4.pt -t "It is well know that deep generative models have a deep latent space!" -i 0

---

Loaded checkpoint 'models/flowtron_ljs.pt')
Number of speakers : 1
Traceback (most recent call last):
  File "inference.py", line 122, in <module>
    args.n_frames, args.sigma, args.seed)
  File "inference.py", line 80, in infer
    audio = waveglow.infer(mels.half(), sigma=0.8).float()
  File "tacotron2/waveglow\glow.py", line 276, in infer
    output = self.WN[k]((audio_0, spect))
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "tacotron2/waveglow\glow.py", line 161, in forward
    self.cond_layers[i](spect),
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'WN' object has no attribute 'cond_layers'

**Comment by rafaelvalle** [comment]
Use the script below to convert the model `https://github.com/NVIDIA/waveglow/blob/master/convert_model.py`

**Comment by erekgit** [comment]
@rafaelvalle This conversion executed successfully, but the same results on the inference demo:

 python convert_model.py ..\flowtron\models\waveglow_256channels_v4.pt ..\flowtron\models\waveglow_256channels_v4_new.pt
F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
f class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's   warnings.warn(msg, SourceChangeWarning)

---
Loaded checkpoint 'models/flowtron_ljs.pt')
Number of speakers : 1
Traceback (most recent call last):
  File "inference.py", line 122, in <module>
    args.n_frames, args.sigma, args.seed)
  File "inference.py", line 80, in infer
    audio = waveglow.infer(mels.half(), sigma=0.8).float()
  File "tacotron2/waveglow\glow.py", line 276, in infer
    output = self.WN[k]((audio_0, spect))
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "tacotron2/waveglow\glow.py", line 161, in forward
    self.cond_layers[i](spect),
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'WN' object has no attribute 'cond_layers'

**Comment by rafaelvalle** [comment]
Convert and use the new saved model

**Comment by erekgit** [comment]
yes, did try, 

my experience is similar to this other issue. i tried v2 and it does execute (though i was expecting to hear an audio output and heard nothing, perhaps i misunderstand the inference demo)


https://github.com/NVIDIA/tacotron2/issues/333#issuecomment-613774631

**Comment by artemg** [comment]
It seems that tecotron2 repo is using old waveglow.
```
cd tacotron2/waveglow
git checkout master
```
And then do the inference without conversion (just original waveglow_256channels_v4.pt you posted).

**Comment by rafaelvalle** [comment]
Please pull from master and try again. We updated the tacotron2 repo in Flowtron.

**Comment by erekgit** [comment]
this is resolved now
