### ISSUE TITLE
What are the attention_weights_1 and attention_weights_2 ?

### ISSUE THREAD

**Issue by youmebangbang** [NVIDIA/flowtron#30]
I have success with using nvidia's tacotron2 repo and understanding alignment with that, but what are these 2 other alignments shown on tensorboard?  I see that attention_weights_0 is being updated but the other 2 attentions are still at step 0.  Thanks.

**Comment by rafaelvalle** [comment]
It shows the alignments for each step of flow. In our default setup odd steps of flow attend to mels in the forward direction while even steps of flow attend to the mel in the forward direction.

**Comment by youmebangbang** [comment]
K thanks

**Comment by Cortexelus** [comment]
@rafaelvalle Was that a typo? Both odd and even steps attend to the forward direction?

**Comment by kevjshih** [comment]
@Cortexelus Yep that's a typo. The flow reverses directions every other step.
