### ISSUE TITLE
How is interpolation between speakers performed?

### ISSUE THREAD

**Issue by youmebangbang** [NVIDIA/flowtron#33]
I have success adjusting sigma values and now reading about the interpolation between speakers: "First, we perform inference by sampling z ∼ N (0, 0.5) until we find two z values, zh and zs, that produce mel-spectrograms with Helen’s and Sally’s voice respectively. We then generate samples by performing inference while linearly interpolating between zh and zs."

How would I go about doing this?

**Comment by rafaelvalle** [comment]
there are several ways... here's one that has worked for us:
set gate threshold to 1 and do inference with random z values, storing the z-value if it comes from the speakers you want to interpolate, one z-value per speaker.
interpolate between the two z values and perform inference.

**Comment by youmebangbang** [comment]
Thanks for the info.
