### ISSUE TITLE
Accent transfer?

### ISSUE THREAD

**Issue by machineko** [NVIDIA/flowtron#34]
How did accent transfer was done (Queen's accent on extra samples)?
Its cool idea but i didnt see anything about it in paper :dagger:

**Comment by rafaelvalle** [comment]
The procedure is the same as style transfer. 
We did not have enough time to investigate it so we decided to only share a sample to show that is possible.

**Comment by machineko** [comment]
K thanks, If u guys investigate this some more pleas ping me up in this topic with results (cause when i was using style transfer result was mediocre) :D

**Comment by rafaelvalle** [comment]
Take a look at out notebook for style transfer: https://github.com/NVIDIA/flowtron/blob/master/inference_style_transfer.ipynb

**Comment by eniolasonowo** [comment]
> Take a look at out notebook for style transfer: https://github.com/NVIDIA/flowtron/blob/master/inference_style_transfer.ipynb 

tried runnin it, got a type error when trying to collect **z values**, any help is gratefull
