### ISSUE TITLE
Synthesis by batches

### ISSUE THREAD

**Issue by Yannecc** [NVIDIA/flowtron#36]
Hi! Thank you for the great work!
I am wondering if there is a way to use flowtron for synthesis of MEL spectrograms (or WAV files, eventually) by batches.
Currently, I am only able to feed text sequence and speaker id one by one, which is quite time-consuming.

The addition of an empty dimension  to *text* and *speaker_vecs* inputs at lines 65-66 of [inference.py](https://github.com/NVIDIA/flowtron/blob/master/inference.py) makes me think the model supports batch inputs, at least for training. 

But when I feed bigger tensors to it (end-padding shorter text sequences with 0 so that I can stack them as a tensor) I get this error:

(102 is my sequence length)

Traceback (most recent call last):
  File "inference.py", line 141, in <module>
    args.id, args.n_frames, args.sigma, args.gate, args.seed)
  File "inference.py", line 82, in infer
    residual, speaker_vecs, text, gate_threshold=gate_threshold)
  File "/home/user/dev/flowtron/flowtron.py", line 612, in infer
    [text, speaker_vecs.expand(text.size(0), -1, -1)], 2)
RuntimeError: The expanded size of the tensor (102) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [102, -1, -1].  Tensor sizes: [2, 1, 128]

**Comment by rafaelvalle** [comment]
Yes, it is possible to perform synthesis by batches.
You'll need to adapt the code such that you pass the input lengths and proper handle the gates.
It'd would be probably easier so set the gate threshold to 1, return the gates and prune the output mel-spectrograms using the returned gates at some threshold.

**Comment by Yannecc** [comment]
Thank you for your help!

**Comment by nikich340** [comment]
If anyone is looking for a ready solution, I will post my variant.
Download and put files in flowtron folder: 
[https://pastebin.com/mMPiy9i7](inference_batch_from_csv.py)
[https://pastebin.com/Lwq2bAWk](test.csv)

Run **inference_batch_from_csv.py** as you ran **inference.py** before, but with `--csv_path test.csv` param instead of text input.
Open and edit **test.csv** file for your needs (and change filename if you want to).
