### ISSUE TITLE
inversed 2 flow alingment

### ISSUE THREAD

**Issue by kurbobo** [NVIDIA/flowtron#48]
A trained 1st flow until I had not bad alignment
![image](https://user-images.githubusercontent.com/32241519/88546228-bd352c00-d024-11ea-8751-aeaecd2dc28e.png)
 then trained seconds flow as it was said in previous issues and after a while alignment of the seconds flow became to look like this 
![image](https://user-images.githubusercontent.com/32241519/88546184-ae4e7980-d024-11ea-8de3-8fc868a7638b.png)

which is strange to me because I expected same picture as in 1st flow. Nevertheless, sound is good. So could anybody explain to me why there is such alignment?

**Comment by rafaelvalle** [comment]
All looks good: in our default setup odd steps of flow attend to mels in the forward direction while even steps of flow attend to the mel in the backward direction. Keep training validation loss keeps decreasing!

**Comment by kurbobo** [comment]
and what is the reason for such rule? "odd steps of flow attend to mels in the forward direction while even steps of flow attend to the mel in the backward direction"?

**Comment by rafaelvalle** [comment]
In our experiments we found that inverting the directions provides better likelihood and audio quality.
