### ISSUE TITLE
Back step problem

### ISSUE THREAD

**Issue by VadimOvchinnikovA** [NVIDIA/flowtron#55]
I can't understand. Why are you iterating from 1 in forward method of AR_Back_Step?
``` 
def forward(self, mel, text, mask, out_lens):
        mel = torch.flip(mel, (0, ))
        # backwards flow, send padded zeros back to end
        for k in range(1, mel.size(1)):
            mel[:, k] = mel[:, k].roll(out_lens[k].item(), dims=0)

        mel, log_s, gates, attn = self.ar_step(mel, text, mask, out_lens)

        # move padded zeros back to beginning
        for k in range(1, mel.size(1)):
            mel[:, k] = mel[:, k].roll(-out_lens[k].item(), dims=0)

        return torch.flip(mel, (0, )), log_s, gates, attn
```

**Comment by rafaelvalle** [comment]
mel is of shape (n_frames, batch) and the batch dimension is sorted by decreasing mel length. 
this guarantees that the first sample will not be padded, hence there are no padded zeros to send back to the end.

**Comment by rafaelvalle** [comment]
Heads up that we changed the code to cover cases where the batch with the larger text is does not have the longest mel.
