### ISSUE TITLE
Which version of Python are you using?

### ISSUE THREAD

**Issue by whillas** [NVIDIA/flowtron#65]
Have tried to install with 3.8 and 3.7 on Ubuntu 18.04, CUDA 10.1 and can't get numba to compile?

**Comment by dariocazzani** [comment]
I installed numba 0.48

**Comment by whillas** [comment]
yeah, but against which version of Python?

**Comment by ciscodario** [comment]
3.6.9

**Comment by whillas** [comment]
Ok, I'll give 3.6 a shot, thanks
