### ISSUE TITLE
Plz, check the range in flip mel

### ISSUE THREAD

**Issue by jhjungCode** [NVIDIA/flowtron#67]
I think correct range is from 0 to mel.size(1), but code starts from 1.

        # backwards flow, send padded zeros back to end
        for k in range(1, mel.size(1)):
            mel[:, k] = mel[:, k].roll(out_lens[k].item(), dims=0)

**Comment by rafaelvalle** [comment]
The mel on the first index  has `max_len`, hence no padded values.

**Comment by jhjungCode** [comment]
but, input data is sorted by text length, not mel length.

most mel length increase in proportion to text length.
but in some case, mel length of longest text length is not longest.

**Comment by rafaelvalle** [comment]
Yes, that certainly can happen. We've updated the repo.
