### ISSUE TITLE
What is  the minimum of GPU memory to run flowtron ?

### ISSUE THREAD

**Issue by fabianoluzbr** [NVIDIA/flowtron#72]
Hi guys! There is a minimal gpu memory limitation to run default config.json file. I am using one RTX 2080 TI and I get a "CUDA out of memory error. Tried to allocate..." What is the minimum GPU memory I need to have?

**Comment by rafaelvalle** [comment]
Memory consumption depends both on the length of your audio files and the batch size.

**Comment by fabianoluzbr** [comment]
Great, thanks. Taking into account that the bach_size standard is 1, which audio size is recommended to 2080 Ti 11GB? (in seconds?) Of course I can find out empirically, but if there is a method calculating this, it would be nice.

**Comment by rafaelvalle** [comment]
10 seconds should work.
