### ISSUE TITLE
Inference on Unseen Speakers

### ISSUE THREAD

**Issue by GauriDhande** [NVIDIA/flowtron#76]
First of all, thanks for the amazing work and repository. I am using the Flowtron LibriTTS model to generate the audios. I was wondering, how can I use different speakers (apart from train-clean-100 speakers) to generate audios. Am I supposed to train the pre-trained model again or there is a set of commands that helps the model to adapt to more speakers.

Please help and thank you in advance.

**Comment by cereballo** [comment]
The speaker encoder that is included with this repository only embeds speakers that it has seen in the training data. There is other work that does not have this constraint (i.e. you can encode any speaker you, regardless if it is in the training data), but you would need to build that into this repository. If you would like to use speakers other than that of which is included in train-clean-100, you would need to add them to the training data.

**Comment by GauriDhande** [comment]
@cereballo Thank you. That solves my doubt.
