### ISSUE TITLE
Unable get attention with n_flow=1

### ISSUE THREAD

**Issue by tricky61** [NVIDIA/flowtron#88]
I have checked the previous issue, but still unable get attention
1. I used the provided ljs filelist, and the start and end silence are trimed with librosa.trim.effect, with top_db=30
2. I used the tacotron2 model to warm start the n_flow=1 training, which trained with ljs corpus, even to trim silence, still got good attention. include_layers are: "encoder", "embedding"
after  100k steps, the loss seems stuck between -0.6~-0.5

but I cannot get flowtron's attention. I don't know where is the problem.

**Comment by rafaelvalle** [comment]
set `"use_attn_prior": true` in the config.json file and let us know.
