### ISSUE TITLE
Changing speaker Voice

### ISSUE THREAD

**Issue by shehrum** [NVIDIA/flowtron#99]
Hi team,

Is it possible to change the voice of the TTS model i.e. adapt/finetune it to a new dataset with a different voice such as in this paper: [Cascading ASR + TTS](https://arxiv.org/abs/2010.02434). From what I read in the documentation and samples, its possible to do style transfer, but didn't find anything on voice conversion.

**Comment by rafaelvalle** [comment]
yes, look at the `Fine-tuning for few-shot speech synthesis` in the README.
